### ISSUE TITLE
Сервис - это штука, которая содержит бизнес-логику, у вас же класс для хранения данных

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/kfc#1]
https://github.com/Artyom16RUS/kfc/blob/3b9ebd57f2be51982c22336aaeb8571db1052a0d/src/main/java/Main.java#L4

**Comment by coursar** [comment]
Переименуйте в `Burger`

**Comment by Artyom16RUS** [comment]
I corrected

**Comment by coursar** [comment]
Issue нужно закрывать сообщениями коммита, а не вручную.

**Comment by Artyom16RUS** [comment]
close

**Comment by Artyom16RUS** [comment]
Closes #1

**Comment by Artyom16RUS** [comment]
Closes: # 1
