### ISSUE TITLE
А как же калории, граммы, описание и БЖУ?

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/kfc#2]
https://github.com/Artyom16RUS/kfc/blob/3b9ebd57f2be51982c22336aaeb8571db1052a0d/src/main/java/BurgerService.java#L1-L8

**Comment by Artyom16RUS** [comment]
Я посчитал это лишней информация. Это просто текстовое описание не влияющие на отличительные особенности класса

**Comment by coursar** [comment]
Надо добавить, задача была - спроектировать класс для отображения информации об объекте на странице.
