### ISSUE TITLE
Назовите поля нормально, никаких a, b, c, g, u быть не должно

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/kfc#4]
https://github.com/Artyom16RUS/kfc/blob/4f7f35572c73d7893dd4fbf9a1d0158dbcf7f36a/src/main/java/Burger.java#L11-L13

**Comment by Artyom16RUS** [comment]
fixes #4

**Comment by Artyom16RUS** [comment]
Не работает "_fixes #4_" и "_closes_" тд что бы закрыть issue не вручную

**Comment by coursar** [comment]
А вы пуш-то сделали?

**Comment by coursar** [comment]
На лекции и в видео всё работает, перепроверьте
